repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-added-large-files
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-mod-tidy
      - id: go-fmt
      - id: go-imports    # Install go install -v golang.org/x/tools/cmd/goimports
      - id: no-go-testing
      - id: golangci-lint # Install https://golangci-lint.run/usage/install/#binaries
      - id: go-critic     # Install go install -v github.com/go-critic/go-critic/cmd/gocritic@latest
      - id: go-unit-tests
