apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "baski-server.fullname" . }}
  labels:
    {{- include "baski-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "baski-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "baski-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "baski-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.server.dev}}
          args:
            - -d
          {{- end}}
          env:
            - name: BASKI_S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.existingSecretName }}
                  key: endpoint
            - name: BASKI_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.existingSecretName }}
                  key: accessKey
            - name: BASKI_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.existingSecretName }}
                  key: secretKey
            - name: BASKI_S3_BUCKET
              value: baski
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
