name: Validate on push

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"
    branch:
      - "*"

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true
          args: --timeout=30m
  test:
    name: Run tests
    runs-on: 'ubuntu-22.04'
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
      - run: go test -v -cover ./...

  security-checks:
    runs-on: ubuntu-22.04
    needs: test
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Build Local Baski Image
        uses: drewbernetes/container-security-action@v0.0.2
        if: github.event_name != 'pull_request'
        id: build-and-scan-baski
        with:
          image-repo: "registry.hudson-viles.uk/public"
          repo-username: ${{ secrets.REGISTRY_PUBLIC_USER }}
          repo-password: ${{ secrets.REGISTRY_PUBLIC_PASSWORD }}
          image-name: baski
          image-tag: ${{ github.ref_name }}
          check-severity: CRITICAL
          trivyignore-from-s3: true
          s3-endpoint: "https://api.s3.hudson-viles.uk/"
          s3-access-key: ${{secrets.S3_ACCESS_KEY}}
          s3-secret-key: ${{secrets.S3_SECRET_KEY}}
          s3-bucket: "trivyignores"
          s3-path: "baski"
          add-latest-tag: false
          publish-image: false
          cosign-private-key: ${{secrets.COSIGN_KEY}}
          cosign-password: ${{secrets.COSIGN_PASSWORD}}
          cosign-tlog: false
          dockerfile-path: docker/baski
      - name: Build Local Baski Server Image
        uses: drewbernetes/container-security-action@v0.0.2
        if: github.event_name != 'pull_request'
        id: build-and-scan-server
        with:
          image-repo: "registry.hudson-viles.uk/public"
          repo-username: ${{ secrets.REGISTRY_PUBLIC_USER }}
          repo-password: ${{ secrets.REGISTRY_PUBLIC_PASSWORD }}
          image-name: baski-server
          image-tag: ${{ github.ref_name }}
          check-severity: CRITICAL
          trivyignore-from-s3: true
          s3-endpoint: "https://api.s3.hudson-viles.uk/"
          s3-access-key: ${{secrets.S3_ACCESS_KEY}}
          s3-secret-key: ${{secrets.S3_SECRET_KEY}}
          s3-bucket: "trivyignores"
          s3-path: "baski-server"
          add-latest-tag: false
          publish-image: false
          cosign-private-key: ${{secrets.COSIGN_KEY}}
          cosign-password: ${{secrets.COSIGN_PASSWORD}}
          cosign-tlog: false
          dockerfile-path: docker/server
