name: Build on Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Create Release
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
      - name: Get OS and arch info
        run: |
          GOARCH=amd64
          GOOS=linux
          BINARY_NAME=${{github.repository}}-$GOOS-$GOARCH
          SERVER_BINARY_NAME=${{github.repository}}-server-$GOOS-$GOARCH
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV
      - name: Build Baski
        run: |
          CGO_ENABLED=0 go build -o "$BINARY_NAME" cmd/baski/main.go
      - name: Build Baski-Server
        run: |
          CGO_ENABLED=0 go build -o "$SERVER_BINARY_NAME" cmd/baski/main.go
      - name: Release Notes
        run: |
          git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/RELEASE-TEMPLATE.md"
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          body_path: ".github/RELEASE-TEMPLATE.md"
          draft: false
          files: |
            ${{env.BINARY_NAME}}
            ${{env.SERVER_BINARY_NAME}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
